name: Release Changes

on:
  workflow_run:
    workflows: ["Validate Changes"]
    branches: [main]
    types:
      - completed

jobs:
  begin-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Beginning release."
      - name: 'Download artifacts from triggering workflow'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            let matchArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == 'version.json' || artifact.name == 'PSGallery-package' || artifact.name == 'release-notes.md';
            });
            let downloadsPromises = matchArtifacts.map(async (artifact) => {
              var blob = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip'
              });
              return { name: artifact.name, data: blob.data }
            });
            let downloads = await Promise.all(downloadsPromises);
            let fs = require('fs');
            downloads.forEach((download) => {
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${download.name}.zip`, Buffer.from(download.data));
            });
      - name: Unzip version.json
        shell: pwsh
        run: Expand-Archive -Path "version.json.zip" -DestinationPath ./version/
      - name: Upload version.json
        uses: actions/upload-artifact@v3
        with:
          name: version.json
          path: ./version/version.json
      - name: Unzip PSGallery-package
        shell: pwsh
        run: Expand-Archive -Path "PSGallery-package.zip" -DestinationPath ./package/
      - name: Upload PSGallery-package
        uses: actions/upload-artifact@v3
        with:
          name: PSGallery-package
          path: ./package/*.nupkg
      - name: Unzip release-notes.md
        shell: pwsh
        run: Expand-Archive -Path "release-notes.md.zip" -DestinationPath ./release-notes/
      - name: Upload release-notes.md
        uses: actions/upload-artifact@v3
        with:
          name: release-notes.md
          path: ./release-notes/release-notes.md

  test-publish-psgallery-package:
    runs-on: ubuntu-latest
    needs: [begin-release]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Download PSGallery package
      uses: actions/download-artifact@v2
      with:
        name: PSGallery-package
        path: ./out/
    - name: Publish to PSGallery
      shell: pwsh
      run: ./scripts/publish.ps1 -NUGET_KEY "abc" -WhatIf

  draft-github-release:
    needs: [test-publish-psgallery-package]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Download version.json
      uses: actions/download-artifact@v2
      with:
        name: version.json
        path: ./out/
    - name: Populate GitVersion variables
      id: gitversion_vars
      shell: pwsh
      run: |
        $version = Get-Content -Raw -Path ./out/version.json -Encoding UTF8 | ConvertFrom-Json
        foreach ($key in $version.PSObject.Properties.Name) {
          echo "::set-output name=$key::$($version.$key)"
        }
    - name: Download release-notes.md
      uses: actions/download-artifact@v2
      with:
        name: release-notes.md
        path: ./out/
    - name: Load release notes
      id: load_release_notes
      shell: pwsh
      run: |
        $releaseNotes = (Get-Content -Raw -Path ./out/release-notes.md -Encoding UTF8).Trim()
        echo "::set-output name=release_notes::$releaseNotes"
    - name: Download PSGallery package
      uses: actions/download-artifact@v2
      with:
        name: PSGallery-package
        path: ./out/
    - name: Create release
      id: draft_github_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ steps.gitversion_vars.outputs.FullSemVer }}"
        release_name: "v${{ steps.gitversion_vars.outputs.FullSemVer }}"
        commitish: "${{ steps.gitversion_vars.outputs.Sha }}"
        body: "${{ steps.load_release_notes.outputs.release_notes }}"
        draft: true
        prerelease: "${{ steps.gitversion_vars.outputs.PreReleaseTag != '' }}"
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft_github_release.outputs.upload_url }}
        asset_path: ./PSGallery-package/*.nupkg
        asset_name: ${{ steps.gitversion_vars.outputs.NuGetVersionV2 }}.nupkg
        asset_content_type: application/zip

  publish-psgallery-package:
    runs-on: ubuntu-latest
    needs: [draft-github-release]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Download PSGallery package
      uses: actions/download-artifact@v2
      with:
        name: PSGallery-package
        path: ./out/
    - name: Publish to PSGallery
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      shell: pwsh
      run: ./scripts/publish.ps1 -NUGET_KEY "$env:NUGET_KEY"

  publish-github-release:
    runs-on: ubuntu-latest
    needs: [publish-psgallery-package]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Download version.json
      uses: actions/download-artifact@v2
      with:
        name: version.json
        path: ./out/
    - name: Populate GitVersion variables
      id: gitversion_vars
      shell: pwsh
      run: |
        $version = Get-Content -Path ./out/version.json -Encoding UTF8 | ConvertFrom-Json
        foreach ($key in $version.PSObject.Properties.Name) {
          echo "::set-output name=$key::$($version.$key)"
        }
    - name: Download release-notes.md
      uses: actions/download-artifact@v2
      with:
        name: release-notes.md
        path: ./out/
    - name: Load release notes
      id: load_release_notes
      shell: pwsh
      run: |
        $releaseNotes = (Get-Content -Raw ./out/release-notes.md -Encoding UTF8).Trim()
        echo "::set-output name=release_notes::$releaseNotes"
    - name: Download PSGallery package
      uses: actions/download-artifact@v2
      with:
        name: PSGallery-package
        path: ./out/
    - name: Publish GitHub release
      id: publish_github_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ steps.gitversion_vars.outputs.FullSemVer }}"
        release_name: "v${{ steps.gitversion_vars.outputs.FullSemVer }}"
        commitish: "${{ steps.gitversion_vars.outputs.Sha }}"
        body: "${{ steps.load_release_notes.outputs.release_notes }}"
        draft: false
        prerelease: "${{ steps.gitversion_vars.outputs.PreReleaseTag != '' }}"
